### ISSUE TITLE
'fava.core.fava_options.FavaOptions object' has no attribute 'journal-show'

### ISSUE THREAD

**Issue by lingchingteng** [scauligi/refried#9]
I use docker to run fava and I found an error on Journal page.

This is the error message. 
And I didn't find anything on google, so I create an issue.

thanks!

fava_1  |   File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
fava_1  |     rv = template.render(context)
fava_1  |   File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
fava_1  |     self.environment.handle_exception()
fava_1  |   File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
fava_1  |     raise rewrite_traceback_stack(source=source)
fava_1  |   File "<template>", line 107, in top-level template code
fava_1  | jinja2.exceptions.UndefinedError: 'fava.core.fava_options.FavaOptions object' has no attribute 'journal-show'

**Comment by scauligi** [comment]
Which version of fava are you using? I've currently got it working with `fava, version 1.20.2.dev16+ge31a8425` as I usually update to the latest git commit for fava.

**Comment by lingchingteng** [comment]
I found this change is the root cause.
https://github.com/beancount/fava/commit/233d30a566eda37bfd36877246e2844098da63c8

Modify the g.ledger.fava_options in __init__.py and .html can fix this error.
